// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

/* [Shy Agam - 2019-05-26]
 * This is a modified clone of the file generated by the Angular CLI and it will be used when testing e2e in production.
 * This copy was created `protractor.conf.prod.js` to:
 * - Run Chrome in Headless mode
 * - Generate a JUnit report to be consumed by Azure DevOps
 * 
 * When developing, simply call `ng e2e`.
 * In production, call `npm run e2e` (see `package.json`).
 */
const { SpecReporter } = require('jasmine-spec-reporter');
const { JUnitXmlReporter } = require('jasmine-reporters');

exports.config = {
    allScriptsTimeout: 11000,
    specs: [
        './src/**/*.e2e-spec.ts'
    ],
    capabilities: {
        'browserName': 'chrome',
        chromeOptions: {
            args: ["--headless", "--disable-gpu", "--window-size=800,600"]
        }
    },
    directConnect: true,
    baseUrl: 'http://localhost:4200/',
    framework: 'jasmine',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        print: function() { }
    },
    onPrepare()
    {
        require('ts-node').register({
            project: require('path').join(__dirname, './tsconfig.e2e.json')
        });

        const env = jasmine.getEnv();

        env.addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));

        // [Shy Agam - 2019-05-26] Added JUnit report for consumption in Azure DevOps
        env.addReporter(new JUnitXmlReporter({
            savePath: require('path').join(__dirname, '../../tests/demo-e2e'),
            filePrefix: `TESTS-e2e`,
            consolidateAll: true,
            captureStdout: true
        }));
    }
};