// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

/* [Shy Agam - 2019-05-26]
 * This is the original file generated by the Angular CLI and it will be used when testing e2e at development time.
 * A copy of this file was created as `protractor.conf.prod.js` and will be used for production to:
 * - Run Chrome in Headless mode
 * - Generate a JUnit report to be consumed by Azure DevOps
 * 
 * When developing, simply call `ng e2e`.
 * In production, call `npm run e2e` (see `package.json`).
 */
const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
    allScriptsTimeout: 11000,
    specs: [
        './src/**/*.e2e-spec.ts'
    ],
    capabilities: {
        'browserName': 'chrome'
    },
    directConnect: true,
    baseUrl: 'http://localhost:4200/',
    framework: 'jasmine',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        print: function() { }
    },
    onPrepare()
    {
        require('ts-node').register({
            project: require('path').join(__dirname, './tsconfig.e2e.json')
        });

        const env = jasmine.getEnv();

        env.addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
    }
};